### PR TITLE
Added an environment alert that displays what environment is passed in (DEV, TEST, or SANDBOX)

### PR DESCRIPTION
**Pull request by EPortman**
*Issue #:*
https://github.com/bcgov/entity/issues/<Put the github issue number here>

*Description of changes:*
Added an environment parameter that can be passed either 'DEV', 'TEST', or 'SANDBOX'. If one of these are passed in a banner is displayed showing the environment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by ozamani9gh — APPROVED** [review]
looks good

**Review by ozamani9gh — APPROVED** [review]
looks good

**Comment by seeker25** [comment]
Need to update the package.json and package-lock.json @EPortman that way the npm publish works

**Comment by seeker25** [comment]
image

**Comment by EPortman** [comment]
My mistake. Wil update it now.

**Comment by EPortman** [comment]
I submitted another PR with the version numbers bumped

https://github.com/bcgov/sbc-common-components/pull/358

**Comment by seeker25** [comment]
good stuff, publishing now

**Pull request merged**
