### PR TITLE
12496 - Add in exception handling logging. 

### PR DESCRIPTION
**Pull request by seeker25**
https://github.com/bcgov/entity/issues/12496

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

This way it will display in the logs, and not just be sent over sentry.

In Openshift logs nothing is logged. Although I did get two emails from sentry:
AttributeError: 'NoneType' object has no attribute 'requested_by'

I've reviewed the sentry usage here:
https://docs.sentry.io/platforms/python/guides/logging/

I think it should work fine with sentry still, but wont know until it's on TEST. 

Before (in local dev): ***NOTE THIS DOESNT SHOW UP ON DEV/TEST environment, it's just blank***
```
Traceback (most recent call last):
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 671, in error_router
    return original_handler(f)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 669, in error_router
    return self.handle_error(e)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/cors.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_jwt_oidc/jwt_manager.py", line 224, in wrapper
    return f(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_opentracing/tracing.py", line 82, in wrapper
    r = f(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/resources/fas/routing_slip.py", line 145, in patch
    response, status = RoutingSlipService.update(
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/utils/user_context.py", line 133, in wrapper
    return function(*func_args, **func_kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip.py", line 396, in update
    RoutingSlipStatusTransitionService.validate_possible_transitions(routing_slip, status)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py", line 85, in validate_possible_transitions
    allowed_statuses = RoutingSlipStatusTransitionService.get_possible_transitions(rs_model)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/utils/user_context.py", line 133, in wrapper
    return function(*func_args, **func_kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py", line 71, in get_possible_transitions
    is_same_user = refund_model.requested_by == kwargs['user'].user_name
AttributeError: 'NoneType' object has no attribute 'requested_by'

```

After:

```
2022-06-02 07:16:50,974 - pay_api - ERROR in app:app.py:1891 - log_exception: Exception on /api/v1/fas/routing-slips/298570860 [PATCH]
Traceback (most recent call last):
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_restx/cors.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_jwt_oidc/jwt_manager.py", line 224, in wrapper
    return f(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/venv/lib/python3.8/site-packages/flask_opentracing/tracing.py", line 82, in wrapper
    r = f(*args, **kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/resources/fas/routing_slip.py", line 145, in patch
    response, status = RoutingSlipService.update(
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/utils/user_context.py", line 133, in wrapper
    return function(*func_args, **func_kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip.py", line 396, in update
    RoutingSlipStatusTransitionService.validate_possible_transitions(routing_slip, status)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py", line 85, in validate_possible_transitions
    allowed_statuses = RoutingSlipStatusTransitionService.get_possible_transitions(rs_model)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/utils/user_context.py", line 133, in wrapper
    return function(*func_args, **func_kwargs)
  File "/home/trav/work/sbc-pay/pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py", line 71, in get_possible_transitions
    is_same_user = refund_model.requested_by == kwargs['user'].user_name

### CODE REVIEW

**Comment by seeker25** [comment]
https://flask.palletsprojects.com/en/2.1.x/errorhandling/

"An error handler for Exception might seem useful for changing how all errors, even unhandled ones, are presented to the user. However, this is similar to doing except Exception: in Python, it will capture all otherwise unhandled errors, including all HTTP status codes.

In most cases it will be safer to register handlers for more specific exceptions. Since HTTPException instances are valid WSGI responses, you could also pass them through directly."

Going to see if there is another way to accomplish this.

**Comment by seeker25** [comment]
Flask documentation states to be careful when handling Exception handling. 

I did see LEAR is logging "unhandled exceptions":
https://github.com/bcgov/lear/blob/5f14b2f662c6aceb1fa67a1e49b5c2b05edc35f1/legal-api/src/legal_api/errorhandlers.py#L36

**Comment by seeker25** [comment]
This should also fix exceptions in Sentry where the exception_handler fails, but it's actually a `MultipleResultsFound` exception.

**Review by pwei1018 — APPROVED** [review]

**Comment by seeker25** [comment]
This needs to be tested in `SBC-AUTH` before being merged.

**Pull request merged**
