### PR TITLE
18903 - Update hero img src path. Css class update.

### PR DESCRIPTION
**Pull request by dimak1**
*Issue #:*
- https://github.com/bcgov/entity/issues/18903

*Description of changes:*
- Small updates to resolve hero image path and apply correct css class 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Comment by dimak1** [comment]
@seeker25 for review please

**Comment by seeker25** [comment]
At the vet, when I get back

**Comment by seeker25** [comment]
@dimak1 tests failing?

**Comment by dimak1** [comment]
@seeker25 can you pls re-run it? I don't have access.

**Comment by seeker25** [comment]
@dimak1 publishing

**Pull request merged**
