### PR TITLE
13245 - Staff rework

### PR DESCRIPTION
**Pull request by seeker25**
*Issue #:*
https://github.com/bcgov/entity/issues/13245

*Description of changes:*
Allow an account to show for staff

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

### CODE REVIEW

**Review by kialj876 — APPROVED** [review]

**Comment by severinbeauvais** [comment]
Will this require new builds (with the new import) of Create UI, Edit UI, Filings UI?

**Comment by seeker25** [comment]
Yes, will require new builds with the new import

**Comment by severinbeauvais** [comment]
> Yes, will require new builds with the new import

And is that something you're going to do? 😁 

If you do, note that our team is spending today testing SP/GP end-to-end in Test environment. Also note that Kial wants to deploy Dev -> Test for some projects. If you want to get your code into Test, check with him. Also please update [our release ticket](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13851) if needed.

@kialj876

**Comment by seeker25** [comment]
https://github.com/bcgov/entity/issues/13861

**Pull request merged**
